(function () {
  'use strict';
  if (window.__locatorLensV5) return;
  window.__locatorLensV5 = true;

  const OVR_ID = '__ll5_overlay__';
  const TAG_ID = '__ll5_tag__';
  const FLASH_CLASS = '__ll4flash__';
  const HIGHLIGHT_CLASS = '__ll4highlight__';
  const DIM_CLASS = '__ll4dim__';
  const SAVED_OUTLINE = 'll4OutlinePrev';
  const SAVED_Z = 'll4ZPrev';

  let overlayEl = null;
  let tagEl = null;
  let cycledMatches = [];
  let cycleIndex = 0;

  const state = { picking: false, passive: false, lastTarget: null };

  function xpEsc(str) {
    if (!String(str).includes("'")) return `'${str}'`;
    if (!String(str).includes('"')) return `"${str}"`;
    const parts = String(str).split("'");
    return `concat('${parts.join(`',"'",'`)}')`;
  }
  function cssEsc(str) {
    return (window.CSS && CSS.escape) ? CSS.escape(str) : String(str).replace(/([^\w-])/g, '\\$1');
  }
  function safeQueryAll(selector) {
    try { return Array.from(document.querySelectorAll(selector)); } catch { return []; }
  }
  function safeXPathAll(selector) {
    try {
      const result = document.evaluate(selector, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      const out = [];
      for (let i = 0; i < result.snapshotLength; i++) {
        const item = result.snapshotItem(i);
        if (item && item.nodeType === 1) out.push(item);
      }
      return out;
    } catch {
      return [];
    }
  }
  function countCss(sel) { try { return document.querySelectorAll(sel).length; } catch { return 0; } }
  function countXPath(sel) { return safeXPathAll(sel).length; }
  function getDirectText(el) {
    return Array.from(el.childNodes).filter(n => n.nodeType === Node.TEXT_NODE).map(n => n.textContent).join(' ').replace(/\s+/g, ' ').trim();
  }
  function sanitizeText(text) {
    const firstLine = String(text || '').split('\n').map(line => line.trim()).find(Boolean) || '';
    const asciiSegments = firstLine.split(/[^\x20-\x7E]+/).map(s => s.trim()).filter(Boolean);
    const ascii = asciiSegments.sort((a, b) => b.length - a.length)[0] || firstLine;
    return ascii.split('/')[0].replace(/\s+/g, ' ').trim();
  }
  function extractPhrase(text, maxLen = 65) {
    const cleaned = sanitizeText(text);
    if (!cleaned) return '';
    if (cleaned.length > 50 || /\s{2,}|[|]{2,}/.test(cleaned)) {
      const comma = cleaned.indexOf(',');
      if (comma > 8 && comma <= maxLen) return cleaned.slice(0, comma).trim();
      return cleaned.slice(0, Math.min(50, cleaned.length)).trim();
    }
    if (cleaned.length <= maxLen) return cleaned;
    const comma = cleaned.indexOf(',');
    if (comma > 8 && comma <= maxLen) return cleaned.slice(0, comma).trim();
    return cleaned.slice(0, maxLen).trim();
  }
  function absoluteXpath(el) {
    const parts = [];
    let cur = el;
    while (cur && cur.nodeType === 1) {
      let idx = 1;
      let sib = cur.previousElementSibling;
      while (sib) {
        if (sib.tagName === cur.tagName) idx += 1;
        sib = sib.previousElementSibling;
      }
      parts.unshift(`${cur.tagName.toLowerCase()}[${idx}]`);
      cur = cur.parentElement;
    }
    return '/' + parts.join('/');
  }
  function nthOfType(el) {
    let idx = 1;
    let sib = el.previousElementSibling;
    while (sib) {
      if (sib.tagName === el.tagName) idx += 1;
      sib = sib.previousElementSibling;
    }
    return idx;
  }
  function nthChild(el) {
    let idx = 1;
    let sib = el.previousElementSibling;
    while (sib) { idx += 1; sib = sib.previousElementSibling; }
    return idx;
  }
  function attributeMap(el) {
    return Object.fromEntries(Array.from(el.attributes || []).map(attr => [attr.name, attr.value]));
  }
  function looksAutoGenerated(value) {
    if (!value) return false;
    return /\d/.test(value) || /:r\w+:/.test(value) || /^ember\d+/i.test(value) || /^mui-\d+/i.test(value) || /^[a-f0-9]{8,}$/i.test(value) || /[a-f0-9]{8}-[a-f0-9]{4}-/i.test(value) || value.length > 55;
  }
  function getStableId(id) {
    return id && !looksAutoGenerated(id) ? id : '';
  }
  function isDynamicClass(cls) {
    return !!cls && (/\d/.test(cls) || /__\w{4,}/.test(cls) || /^sc-/.test(cls) || /^css-/.test(cls) || /^[a-zA-Z]{1,3}[A-Z][a-zA-Z0-9]{2,}$/.test(cls) || /^[a-z0-9]{5,8}$/i.test(cls));
  }
  function stableClasses(el) { return Array.from(el.classList || []).filter(cls => !isDynamicClass(cls)); }
  function dynamicClasses(el) { return Array.from(el.classList || []).filter(cls => isDynamicClass(cls)); }
  function accessibleName(el) {
    return el.getAttribute('aria-label') || el.innerText?.trim() || el.getAttribute('alt') || el.getAttribute('title') || '';
  }
  function optimizeXPath(selector) {
    if (!selector.includes('/')) return selector;
    const segments = selector.split('//').filter(Boolean);
    if (segments.length <= 1) return selector;
    for (let i = segments.length - 1; i >= 0; i--) {
      const candidate = '//' + segments.slice(i).join('//');
      if (countXPath(candidate) === 1) return candidate;
    }
    return selector;
  }
  function countForSelector(selector, selectorType) {
    return selectorType === 'xpath' ? countXPath(selector) : countCss(selector);
  }
  function addLocator(locators, seq, loc) {
    const count = countForSelector(loc.selector, loc.selectorType);
    let score = loc.score;
    if (count > 1 && count <= 5) score -= 14;
    else if (count > 5 && count <= 20) score -= 28;
    else if (count > 20) score -= 42;
    if (count === 0) score = 0;
    const item = {
      id: seq.value++,
      ...loc,
      score: Math.max(0, Math.round(score)),
      matchCount: count,
      fieldSeed: loc.meta?.textValue || loc.meta?.attributeValue || loc.label
    };
    locators.push(item);
  }

  function generateCssPath(el) {
    const segments = [];
    let cur = el;
    while (cur && cur.nodeType === 1 && cur !== document.body) {
      const testAttr = ['data-testid', 'data-test', 'data-cy', 'data-qa', 'data-automation-id', 'data-test-id', 'data-e2e'].find(attr => cur.hasAttribute(attr));
      if (testAttr) {
        segments.unshift(`[${testAttr}="${cur.getAttribute(testAttr).replace(/"/g, '\\"')}"]`);
        break;
      }
      const stableId = getStableId(cur.id);
      if (stableId) {
        segments.unshift(`#${cssEsc(stableId)}`);
        break;
      }
      if (cur.getAttribute('aria-label')) {
        segments.unshift(`${cur.tagName.toLowerCase()}[aria-label="${cur.getAttribute('aria-label').replace(/"/g, '\\"')}"]`);
        break;
      }
      const stable = stableClasses(cur);
      if (stable.length) segments.unshift(`${cur.tagName.toLowerCase()}.${cssEsc(stable[0])}`);
      else segments.unshift(`${cur.tagName.toLowerCase()}:nth-of-type(${nthOfType(cur)})`);
      const candidate = segments.join(' > ');
      if (countCss(candidate) === 1) break;
      cur = cur.parentElement;
    }
    return segments.join(' > ');
  }

  function buildRelativeXPath(el) {
    const priority = ['placeholder', 'title', 'value', 'name', 'aria-label', 'alt', 'for', 'data-label', 'role', 'type', 'class'];
    const tag = el.tagName.toLowerCase();
    for (const attr of priority) {
      const value = el.getAttribute(attr);
      if (!value || (attr === 'class' && isDynamicClass(value))) continue;
      const selector = `//${tag}[@${attr}=${xpEsc(value)}]`;
      if (countXPath(selector) === 1) return selector;
    }
    const text = extractPhrase(el.textContent || '');
    if (text) {
      const selector = optimizeXPath(`//${tag}[contains(normalize-space(),${xpEsc(text)})]`);
      if (countXPath(selector) >= 1) return selector;
    }
    return optimizeXPath(absoluteXpath(el));
  }

  function generateLocators(el) {
    const tag = el.tagName.toLowerCase();
    const attrs = attributeMap(el);
    const id = el.id || '';
    const idStable = !!getStableId(id);
    const rawText = (el.textContent || '').replace(/\s+/g, ' ').trim();
    const textPreview = extractPhrase(rawText, 65);
    const fullTextPreview = rawText.slice(0, 200);
    const locators = [];
    const seq = { value: 0 };
    const role = el.getAttribute('role') || '';
    const accName = accessibleName(el);
    const placeholder = el.getAttribute('placeholder') || '';
    const title = el.getAttribute('title') || '';
    const alt = el.getAttribute('alt') || '';
    const href = el.getAttribute('href') || '';
    const value = el.getAttribute('value') || '';
    const name = el.getAttribute('name') || '';
    const stable = stableClasses(el);
    const dynamic = dynamicClasses(el);

    ['data-testid', 'data-test', 'data-cy', 'data-qa', 'data-automation-id', 'data-test-id', 'data-e2e'].forEach(attr => {
      const val = el.getAttribute(attr);
      if (!val) return;
      addLocator(locators, seq, { category: 'test', type: attr, label: `Test attribute ${attr}`, selector: `[${attr}="${val.replace(/"/g, '\\"')}"]`, selectorType: 'css', score: 95, reason: `Uses ${attr}, which is typically the most stable automation hook.`, meta: { attributeName: attr, attributeValue: val } });
      addLocator(locators, seq, { category: 'test', type: `${attr}-xpath`, label: `Test attribute ${attr}`, selector: `//*[@${attr}=${xpEsc(val)}]`, selectorType: 'xpath', score: 95, reason: `XPath fallback for ${attr}.`, meta: { attributeName: attr, attributeValue: val } });
    });
    if (attrs['aria-label']) addLocator(locators, seq, { category: 'aria', type: 'aria-label', label: 'ARIA label', selector: `[aria-label="${attrs['aria-label'].replace(/"/g, '\\"')}"]`, selectorType: 'css', score: 87, reason: 'Accessible labels are usually stable and human-readable.', meta: { attributeName: 'aria-label', attributeValue: attrs['aria-label'] } });
    if (role && accName) addLocator(locators, seq, { category: 'logical', type: 'role+text', label: 'Role + accessible name', selector: `//*[@role=${xpEsc(role)} and contains(normalize-space(),${xpEsc(extractPhrase(accName, 40))})]`, selectorType: 'xpath', score: 85, reason: 'Combines semantic role with visible or accessible text.', meta: { role, textValue: extractPhrase(accName, 40) } });
    if (attrs['aria-labelledby']) addLocator(locators, seq, { category: 'aria', type: 'aria-labelledby', label: 'ARIA labelledby', selector: `//*[@aria-labelledby=${xpEsc(attrs['aria-labelledby'])}]`, selectorType: 'xpath', score: 78, reason: 'Anchors on linked accessible naming.', meta: { attributeName: 'aria-labelledby', attributeValue: attrs['aria-labelledby'] } });

    if (idStable) addLocator(locators, seq, { category: 'id', type: 'stable-id', label: 'Stable ID', selector: `#${cssEsc(id)}`, selectorType: 'css', score: 90, reason: 'ID passed the stability filters.', meta: { attributeName: 'id', attributeValue: id } });
    if (id && !idStable) addLocator(locators, seq, { category: 'id', type: 'auto-id', label: 'Auto-generated ID', selector: `//*[@id=${xpEsc(id)}]`, selectorType: 'xpath', score: 18, reason: 'Generated as fallback only.', warning: 'POSSIBLY DYNAMIC — verify stability before using.', meta: { attributeName: 'id', attributeValue: id } });
    if (name) addLocator(locators, seq, { category: 'attr', type: 'name', label: 'Name attribute', selector: `[name="${name.replace(/"/g, '\\"')}"]`, selectorType: 'css', score: 80, reason: 'Useful for form fields.', meta: { attributeName: 'name', attributeValue: name } });
    if (placeholder) addLocator(locators, seq, { category: 'attr', type: 'placeholder', label: 'Placeholder', selector: `//*[@placeholder=${xpEsc(placeholder)}]`, selectorType: 'xpath', score: 72, reason: 'Helpful when placeholders are product copy.', meta: { attributeName: 'placeholder', attributeValue: placeholder } });
    if (alt) addLocator(locators, seq, { category: 'attr', type: 'alt', label: 'Alt text', selector: `//*[@alt=${xpEsc(alt)}]`, selectorType: 'xpath', score: 74, reason: 'Strong for images and icon buttons.', meta: { attributeName: 'alt', attributeValue: alt } });
    if (title) addLocator(locators, seq, { category: 'attr', type: 'title', label: 'Title attribute', selector: `//*[@title=${xpEsc(title)}]`, selectorType: 'xpath', score: 63, reason: 'A lightweight attribute fallback.', meta: { attributeName: 'title', attributeValue: title } });
    if (href && tag === 'a' && href !== '#' && href !== '/') addLocator(locators, seq, { category: 'attr', type: 'href', label: 'Href anchor', selector: `//a[contains(@href,${xpEsc(href.replace(/[?#].*$/, '').split('/').filter(Boolean).pop() || href)})]`, selectorType: 'xpath', score: 65, reason: 'Uses a non-trivial href fingerprint.', meta: { attributeName: 'href', attributeValue: href } });
    if (value && (tag === 'input' || tag === 'button')) addLocator(locators, seq, { category: 'attr', type: 'value', label: 'Value attribute', selector: `//*[@value=${xpEsc(value)}]`, selectorType: 'xpath', score: 68, reason: 'Good for submit and button controls.', meta: { attributeName: 'value', attributeValue: value } });

    stable.slice(0, 3).forEach(cls => addLocator(locators, seq, { category: 'class', type: 'stable-class', label: `Stable class ${cls}`, selector: `//${tag}[contains(@class,${xpEsc(cls)})]`, selectorType: 'xpath', score: 45, reason: 'Stable class fragment locator.', meta: { attributeName: 'class', attributeValue: cls } }));
    if (stable.length >= 2) addLocator(locators, seq, { category: 'class', type: 'stable-class-multi', label: 'Multiple stable classes', selector: `//${tag}[contains(@class,${xpEsc(stable[0])}) and contains(@class,${xpEsc(stable[1])})]`, selectorType: 'xpath', score: 52, reason: 'Combines stable classes for extra precision.' });
    dynamic.slice(0, 2).forEach(cls => addLocator(locators, seq, { category: 'class', type: 'dynamic-class', label: `Dynamic class ${cls}`, selector: `//${tag}[contains(@class,${xpEsc(cls)})]`, selectorType: 'xpath', score: 28, reason: 'Retained as a fallback even though the class looks generated.', warning: 'POSSIBLY DYNAMIC — verify stability before using', meta: { attributeName: 'class', attributeValue: cls } }));
    if (dynamic[0]) {
      let ancestorClass = '';
      let cur = el.parentElement;
      while (cur && !ancestorClass) {
        ancestorClass = stableClasses(cur)[0] || '';
        cur = cur.parentElement;
      }
      if (ancestorClass) addLocator(locators, seq, { category: 'class', type: 'dynamic-class-scoped', label: 'Dynamic class scoped', selector: `//*[contains(@class,${xpEsc(ancestorClass)})]//${tag}[contains(@class,${xpEsc(dynamic[0])})]`, selectorType: 'xpath', score: 40, reason: 'Scopes a dynamic class to a stable ancestor.' });
    }

    const directText = extractPhrase(getDirectText(el), 65);
    if (directText && !el.children.length) addLocator(locators, seq, { category: 'text', type: 'text-exact', label: 'Exact text', selector: `//${tag}[text()=${xpEsc(directText)}]`, selectorType: 'xpath', score: 52, reason: 'Leaf exact-text locator.', meta: { textValue: directText } });
    if (textPreview) addLocator(locators, seq, { category: 'text', type: 'text-normalize', label: 'Normalized text', selector: `//${tag}[normalize-space()=${xpEsc(textPreview)}]`, selectorType: 'xpath', score: 68, reason: 'Normalized text handles whitespace variation.', meta: { textValue: textPreview } });
    if (rawText.length > 50 && textPreview) addLocator(locators, seq, { category: 'text', type: 'text-contains', label: 'Text contains', selector: `//${tag}[contains(normalize-space(),${xpEsc(textPreview)})]`, selectorType: 'xpath', score: 64, reason: 'Uses the first natural phrase for longer content.', meta: { textValue: textPreview } });
    if (tag === 'a' && textPreview) {
      addLocator(locators, seq, { category: 'text', type: 'link-text', label: 'Link text', selector: `//a[normalize-space(.)=${xpEsc(textPreview)}]`, selectorType: 'xpath', score: 68, reason: 'Exact link text locator.', meta: { textValue: textPreview } });
      addLocator(locators, seq, { category: 'text', type: 'partial-link-text', label: 'Partial link text', selector: `//a[contains(text(),${xpEsc(textPreview.slice(0, 30))})]`, selectorType: 'xpath', score: 58, reason: 'Shorter link text fingerprint.', meta: { textValue: textPreview.slice(0, 30) } });
    }

    Array.from(el.querySelectorAll('a[href]')).slice(0, 2).forEach(child => {
      const childHref = child.getAttribute('href');
      const fragment = childHref?.split('/').filter(Boolean).pop();
      if (fragment) addLocator(locators, seq, { category: 'hierarchy', type: 'child-anchor', label: 'Child anchor href', selector: `//${tag}[.//a[contains(@href,${xpEsc(fragment)})]]`, selectorType: 'xpath', score: 70, reason: 'Uses a descendant link as a stable fingerprint.' });
    });
    Array.from(el.querySelectorAll('b,strong')).slice(0, 1).forEach(child => {
      const t = extractPhrase(child.textContent || '', 40);
      if (t) addLocator(locators, seq, { category: 'hierarchy', type: 'child-bold-text', label: 'Child bold text', selector: `//${tag}[.//${child.tagName.toLowerCase()}[normalize-space()=${xpEsc(t)}]]`, selectorType: 'xpath', score: 65, reason: 'Anchors on emphasized descendant text.' });
    });

    const parent = el.parentElement;
    if (parent) {
      const pId = getStableId(parent.id || '');
      const pTag = parent.tagName.toLowerCase();
      const childIdx = nthChild(el);
      if (pId) {
        addLocator(locators, seq, { category: 'hierarchy', type: 'ancestor-descendant', label: 'Ancestor descendant', selector: `#${cssEsc(pId)} ${tag}`, selectorType: 'css', score: 78, reason: 'Uses a stable parent ID anchor.' });
        addLocator(locators, seq, { category: 'hierarchy', type: 'parent-child', label: 'Parent child', selector: `#${cssEsc(pId)} > ${tag}:nth-child(${childIdx})`, selectorType: 'css', score: 74, reason: 'Direct child relationship from stable parent.' });
      }
      const labelSibling = parent.querySelector('label');
      if ((tag === 'input' || tag === 'textarea' || tag === 'select') && labelSibling) {
        const labelText = extractPhrase(labelSibling.textContent || '', 40);
        if (labelText) addLocator(locators, seq, { category: 'hierarchy', type: 'following-sibling', label: 'Following sibling', selector: `//label[normalize-space()=${xpEsc(labelText)}]/following-sibling::${tag}[1]`, selectorType: 'xpath', score: 60, reason: 'Anchors off a nearby label.', meta: { textValue: labelText } });
      }
      const prev = el.previousElementSibling;
      if (prev) addLocator(locators, seq, { category: 'hierarchy', type: 'preceding-sibling', label: 'Preceding sibling', selector: `//${prev.tagName.toLowerCase()}[${nthOfType(prev)}]/following-sibling::${tag}[1]`, selectorType: 'xpath', score: 55, reason: 'Uses sibling position as fallback.' });
      if (role && textPreview) addLocator(locators, seq, { category: 'logical', type: 'role-text', label: 'Role + text', selector: `//*[@role=${xpEsc(role)} and contains(normalize-space(),${xpEsc(textPreview)})]`, selectorType: 'xpath', score: 72, reason: 'Dual anchor using semantics and text.', meta: { role, textValue: textPreview } });
      if (stable[0] && textPreview) addLocator(locators, seq, { category: 'logical', type: 'class-text', label: 'Class + text', selector: `//${tag}[contains(@class,${xpEsc(stable[0])}) and contains(normalize-space(),${xpEsc(textPreview)})]`, selectorType: 'xpath', score: 63, reason: 'Combines a stable class with text.', meta: { textValue: textPreview } });
      if (dynamic[0] && textPreview) addLocator(locators, seq, { category: 'logical', type: 'dynclass-text', label: 'Dynamic class + text', selector: `//${tag}[contains(@class,${xpEsc(dynamic[0])}) and contains(normalize-space(),${xpEsc(textPreview)})]`, selectorType: 'xpath', score: 55, reason: 'Dual anchor fallback when class or text changes independently.', warning: 'POSSIBLY DYNAMIC — verify stability before using', meta: { textValue: textPreview } });
    }

    if (id && !idStable) {
      const stablePrefix = id.match(/^[A-Za-z_-]+/)?.[0];
      if (stablePrefix) addLocator(locators, seq, { category: 'id', type: 'id-starts-with', label: 'ID prefix', selector: `//${tag}[starts-with(@id,${xpEsc(stablePrefix)})]`, selectorType: 'xpath', score: 42, reason: 'Uses only the stable-looking ID prefix.', meta: { attributeName: 'id', attributeValue: stablePrefix } });
    }

    const cssPath = generateCssPath(el);
    if (cssPath) addLocator(locators, seq, { category: 'css', type: 'css-path', label: 'CSS path', selector: cssPath, selectorType: 'css', score: cssPath.includes('nth-of-type') ? 30 : cssPath.startsWith('#') ? 78 : cssPath.includes('data-') ? 82 : cssPath.includes('aria-label') ? 75 : 50, reason: 'Anchored CSS path that stops once unique.', meta: { attributeName: 'cssPath', attributeValue: cssPath } });
    const relativeXPath = buildRelativeXPath(el);
    if (relativeXPath) addLocator(locators, seq, { category: 'xpath', type: 'relative-xpath', label: 'Relative XPath', selector: relativeXPath, selectorType: 'xpath', score: 70, reason: 'Built from preferred attributes with optimization.', meta: { attributeName: 'xpath', attributeValue: relativeXPath } });
    addLocator(locators, seq, { category: 'position', type: 'position-xpath', label: 'Position-based XPath', selector: `(//${tag})[${nthOfType(el)}]`, selectorType: 'xpath', score: 20, reason: 'Pure positional fallback and intentionally fragile.' });
    addLocator(locators, seq, { category: 'absolute', type: 'absolute-xpath', label: 'Absolute XPath', selector: absoluteXpath(el), selectorType: 'xpath', score: 8, reason: 'Full DOM path fallback only.' });

    const rank = item => item.type === 'absolute-xpath' ? 9999 : item.type === 'position-xpath' ? 9998 : -item.score;
    locators.sort((a, b) => rank(a) - rank(b));

    const rect = el.getBoundingClientRect();
    return {
      tag,
      id: id || null,
      idStable,
      attributes: attrs,
      classes: Array.from(el.classList || []),
      classInfo: { stable, dynamic },
      textPreview,
      fullTextPreview,
      rect: { x: Math.round(rect.x), y: Math.round(rect.y), w: Math.round(rect.width), h: Math.round(rect.height) },
      childCount: el.children.length,
      computedStyles: pickStyles(getComputedStyle(el)),
      referenceCounts: {
        id: id ? countCss(`#${cssEsc(id)}`) : 0,
        class: stable[0] ? countCss(`.${cssEsc(stable[0])}`) : 0,
        tag: countCss(tag),
        name: name ? countCss(`[name="${name.replace(/"/g, '\\"')}"]`) : 0,
        ariaLabel: attrs['aria-label'] ? countCss(`[aria-label="${attrs['aria-label'].replace(/"/g, '\\"')}"]`) : 0,
        linkText: tag === 'a' && textPreview ? countXPath(`//a[normalize-space(.)=${xpEsc(textPreview)}]`) : 0,
        cssPath: cssPath ? countCss(cssPath) : 0,
        xpath: relativeXPath ? countXPath(relativeXPath) : 0
      },
      locators
    };
  }

  function pickStyles(style) {
    return {
      display: style.display,
      visibility: style.visibility,
      cursor: style.cursor,
      'pointer-events': style.pointerEvents,
      'font-size': style.fontSize,
      'font-weight': style.fontWeight
    };
  }

  function ensureOverlay() {
    if (overlayEl) return;
    overlayEl = document.createElement('div');
    overlayEl.id = OVR_ID;
    tagEl = document.createElement('div');
    tagEl.id = TAG_ID;
    overlayEl.appendChild(tagEl);
    document.documentElement.appendChild(overlayEl);
  }
  function showOverlay(el, color = '#6366f1', bg = 'rgba(99,102,241,0.07)') {
    ensureOverlay();
    const r = el.getBoundingClientRect();
    Object.assign(overlayEl.style, {
      position: 'fixed', top: `${r.top}px`, left: `${r.left}px`, width: `${r.width}px`, height: `${r.height}px`, display: 'block', pointerEvents: 'none', zIndex: '2147483646', outline: `2px solid ${color}`, background: bg, boxSizing: 'border-box'
    });
    tagEl.textContent = `${el.tagName.toLowerCase()} • ${Math.round(r.width)}×${Math.round(r.height)}`;
    Object.assign(tagEl.style, {
      position: 'absolute', bottom: '100%', left: '0', background: color, color: '#fff', fontSize: '10px', fontFamily: 'monospace', padding: '2px 6px', borderRadius: '4px 4px 0 0', whiteSpace: 'nowrap'
    });
  }
  function hideOverlay() { if (overlayEl) overlayEl.style.display = 'none'; }

  function clearEffects() {
    document.querySelectorAll(`.${FLASH_CLASS}, .${HIGHLIGHT_CLASS}`).forEach(el => {
      el.classList.remove(FLASH_CLASS, HIGHLIGHT_CLASS);
      if (el.dataset[SAVED_OUTLINE] !== undefined) {
        el.style.outline = el.dataset[SAVED_OUTLINE];
        delete el.dataset[SAVED_OUTLINE];
      }
      if (el.dataset[SAVED_Z] !== undefined) {
        el.style.zIndex = el.dataset[SAVED_Z];
        delete el.dataset[SAVED_Z];
      }
    });
    document.querySelectorAll(`.${DIM_CLASS}`).forEach(el => el.classList.remove(DIM_CLASS));
    cycledMatches = [];
    cycleIndex = 0;
  }
  function applyFlash(nodes) {
    clearEffects();
    nodes.forEach(el => {
      el.dataset[SAVED_OUTLINE] = el.style.outline || '';
      el.dataset[SAVED_Z] = el.style.zIndex || '';
      el.classList.add(FLASH_CLASS);
      el.style.zIndex = '2147483640';
    });
  }
  function applyHighlight(nodes) {
    clearEffects();
    const protectedSet = new Set();
    nodes.forEach(node => {
      let cur = node;
      while (cur && cur.nodeType === 1) { protectedSet.add(cur); cur = cur.parentElement; }
      node.querySelectorAll('*').forEach(child => protectedSet.add(child));
    });
    document.body.querySelectorAll('*').forEach(el => {
      if (!protectedSet.has(el)) el.classList.add(DIM_CLASS);
    });
    nodes.forEach(el => {
      el.dataset[SAVED_OUTLINE] = el.style.outline || '';
      el.dataset[SAVED_Z] = el.style.zIndex || '';
      el.classList.add(HIGHLIGHT_CLASS);
      el.style.zIndex = '2147483642';
    });
  }
  function resolveMatches(selector, selectorType) {
    return selectorType === 'xpath' ? safeXPathAll(selector) : safeQueryAll(selector);
  }
  function flashSelector(selector, selectorType, mode = 'flash') {
    const matches = resolveMatches(selector, selectorType).slice(0, 50);
    if (!matches.length) {
      clearEffects();
      return;
    }
    cycledMatches = matches;
    cycleIndex = 0;
    if (mode === 'highlight') applyHighlight(matches);
    else applyFlash(matches);
    matches[0].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'center' });
  }
  function cycleMatch(selector, selectorType, direction = 'next') {
    const matches = resolveMatches(selector, selectorType);
    if (!matches.length) return;
    cycledMatches = matches;
    cycleIndex = direction === 'prev' ? (cycleIndex - 1 + matches.length) % matches.length : (cycleIndex + 1) % matches.length;
    applyHighlight([matches[cycleIndex]]);
    matches[cycleIndex].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'center' });
  }

  function onPickMove(e) {
    const target = e.composedPath?.()[0] || e.target;
    if (!target || target === overlayEl || target === tagEl || target.nodeType !== 1) return;
    state.lastTarget = target;
    showOverlay(target);
  }
  function onPickClick(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    e.stopPropagation();
    const target = e.composedPath?.()[0] || e.target;
    if (!target || target === overlayEl || target === tagEl || target.nodeType !== 1) return;
    showOverlay(target, '#10b981', 'rgba(16,185,129,.10)');
    setTimeout(hideOverlay, 600);
    stopPick();
    chrome.runtime.sendMessage({ type: 'locatorsGenerated', payload: generateLocators(target) });
  }
  function onPickKey(e) {
    if (e.key === 'Escape') {
      stopPick();
      chrome.runtime.sendMessage({ type: 'pickingCancelled' });
    }
  }
  function startPick() {
    state.picking = true;
    document.documentElement.style.cursor = 'crosshair';
    document.addEventListener('mousemove', onPickMove, true);
    document.addEventListener('click', onPickClick, true);
    document.addEventListener('keydown', onPickKey, true);
  }
  function stopPick() {
    state.picking = false;
    document.documentElement.style.cursor = '';
    hideOverlay();
    document.removeEventListener('mousemove', onPickMove, true);
    document.removeEventListener('click', onPickClick, true);
    document.removeEventListener('keydown', onPickKey, true);
  }
  function onPassiveClick(e) {
    if (!state.passive || state.picking) return;
    const target = e.composedPath?.()[0] || e.target;
    if (!target || target === overlayEl || target === tagEl || target.nodeType !== 1) return;
    showOverlay(target, '#10b981', 'rgba(16,185,129,.10)');
    setTimeout(hideOverlay, 600);
    chrome.runtime.sendMessage({ type: 'locatorsGenerated', payload: generateLocators(target) });
  }
  document.addEventListener('click', onPassiveClick, true);

  function validateSelector(selector, selectorType) {
    try {
      const nodes = resolveMatches(selector, selectorType);
      return {
        selector,
        selectorType,
        count: nodes.length,
        error: null,
        preview: nodes.slice(0, 5).map(node => ({ tag: node.tagName.toLowerCase(), text: extractPhrase(node.textContent || node.getAttribute('aria-label') || node.id || '', 80) || '—' }))
      };
    } catch (err) {
      return { selector, selectorType, count: 0, error: err.message, preview: [] };
    }
  }

  chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
    switch (msg.type) {
      case 'ping': sendResponse({ pong: true }); break;
      case 'startPicking': startPick(); sendResponse({ ok: true }); break;
      case 'stopPicking': stopPick(); sendResponse({ ok: true }); break;
      case 'setPassive': state.passive = !!msg.enabled; sendResponse({ ok: true }); break;
      case 'flashLocator': flashSelector(msg.selector, msg.selectorType, msg.mode || 'flash'); sendResponse({ ok: true }); break;
      case 'clearFlash': clearEffects(); sendResponse({ ok: true }); break;
      case 'cycleMatch': cycleMatch(msg.selector, msg.selectorType, msg.direction); sendResponse({ ok: true }); break;
      case 'validateSelector': sendResponse(validateSelector(msg.selector, msg.selectorType)); break;
      default: sendResponse({ ok: false });
    }
    return true;
  });
})();
