// LocatorLens v5 — Content Script
// Locator engine + pick/passive overlay
(function () {
  'use strict';
  if (window.__locatorLensV5) return;
  window.__locatorLensV5 = true;

  // ═══════════════════════════════════════════════════════════════
  //  UTILITY
  // ═══════════════════════════════════════════════════════════════

  const OVR_ID  = '__ll5_overlay__';
  const TAG_ID  = '__ll5_tag__';
  let overlayEl = null;
  let tagEl     = null;

  /* Detect IDs auto-generated by frameworks */
  function looksAutoGenerated(id) {
    if (!id) return true;
    if (/^:r[0-9a-z]+:$/i.test(id)) return true;                  // React 18+
    if (/^ember\d+$/i.test(id)) return true;                       // Ember
    if (/^react-select-\d/i.test(id)) return true;                 // react-select
    if (/^(mui|ng|v|rc|el|ant|headlessui)-/.test(id)) return true; // Material/Angular/Vue/Ant
    if (/^radix-/.test(id)) return true;                           // Radix
    if (/^[a-f0-9]{8,}$/i.test(id)) return true;                  // hex hashes
    if (/\d{4,}/.test(id) && !/\b(zip|code|phone|year|date)\b/i.test(id)) return true;
    return false;
  }

  /* Detect dynamically-generated class names */
  function isDynamicClass(cls) {
    if (!cls) return false;
    if (/^[a-zA-Z]{1,4}[A-Z][a-zA-Z]{1,6}$/.test(cls)) return true;   // camelCase hashes like l9NsEV
    if (/^css-[a-z0-9]+$/i.test(cls)) return true;                     // emotion
    if (/^_[a-z0-9]{5,}$/i.test(cls)) return true;                     // CSS modules
    if (/^[a-z]{1,3}-[a-f0-9]{4,}/i.test(cls)) return true;           // generic hash
    if (/^sc-[a-zA-Z]/.test(cls)) return true;                         // styled-components
    if (/^svelte-[a-z0-9]+$/i.test(cls)) return true;                  // Svelte
    return false;
  }

  /* Escape a string for use in XPath expressions */
  function xpEsc(str) {
    if (!str.includes("'")) return `'${str}'`;
    if (!str.includes('"')) return `"${str}"`;
    const parts = str.split("'");
    return `concat('${parts.join("',\"'\",'")}')`;
  }

  /* Escape a string for CSS selectors */
  function cssEsc(str) {
    return CSS.escape ? CSS.escape(str) : str.replace(/([^\w-])/g, '\\$1');
  }

  /* Extract a short phrase from potentially long text */
  function extractPhrase(text, maxLen) {
    maxLen = maxLen || 55;
    const trimmed = text.trim().replace(/\s+/g, ' ');
    if (trimmed.length <= maxLen) return trimmed;
    // Try to cut at sentence boundary
    const sentEnd = trimmed.indexOf('. ');
    if (sentEnd > 0 && sentEnd <= maxLen) return trimmed.slice(0, sentEnd);
    // Cut at comma
    const commaEnd = trimmed.indexOf(', ');
    if (commaEnd > 0 && commaEnd <= maxLen) return trimmed.slice(0, commaEnd);
    // Cut at last space before maxLen
    const spaceIdx = trimmed.lastIndexOf(' ', maxLen);
    if (spaceIdx > 10) return trimmed.slice(0, spaceIdx);
    return trimmed.slice(0, maxLen);
  }

  /* Count matches for a CSS selector */
  function cssCount(sel) {
    try { return document.querySelectorAll(sel).length; }
    catch { return -1; }
  }

  /* Count matches for an XPath expression */
  function xpCount(expr) {
    try {
      const r = document.evaluate(expr, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      return r.snapshotLength;
    } catch { return -1; }
  }

  /* Build the full XPath from the root to an element */
  function absoluteXpath(el) {
    const parts = [];
    let cur = el;
    while (cur && cur.nodeType === 1) {
      let idx = 1;
      let sib = cur.previousElementSibling;
      while (sib) {
        if (sib.nodeName === cur.nodeName) idx++;
        sib = sib.previousElementSibling;
      }
      const tag = cur.nodeName.toLowerCase();
      parts.unshift(`${tag}[${idx}]`);
      cur = cur.parentElement;
    }
    return '/' + parts.join('/');
  }

  /* Get nth-child index */
  function nthIndex(el) {
    let idx = 1;
    let sib = el.previousElementSibling;
    while (sib) { idx++; sib = sib.previousElementSibling; }
    return idx;
  }

  /* Gather all interesting attributes */
  function gatherAttrs(el) {
    const out = {};
    for (const attr of el.attributes) {
      out[attr.name] = attr.value;
    }
    return out;
  }

  // ═══════════════════════════════════════════════════════════════
  //  LOCATOR ENGINE
  // ═══════════════════════════════════════════════════════════════

  function generateLocators(el) {
    const tag  = el.tagName.toLowerCase();
    const id   = el.id || '';
    const name = el.getAttribute('name') || '';
    const type = el.getAttribute('type') || '';
    const rawText = (el.textContent || '').trim();
    const ownText = getDirectText(el).trim();
    const attrs = gatherAttrs(el);
    const classList = Array.from(el.classList || []);
    const rect = el.getBoundingClientRect();

    const locators = [];
    let seq = 0;

    function add(category, label, selector, selectorType, scoreBase, extra) {
      const count = selectorType === 'xpath' ? xpCount(selector) : cssCount(selector);
      let score = scoreBase;
      if (count === 1) score = Math.min(score + 15, 100);
      else if (count > 1 && count <= 5) score = Math.max(score - 10, 5);
      else if (count > 5) score = Math.max(score - 25, 2);
      if (count < 0) score = Math.max(score - 30, 1);

      locators.push({
        id: seq++,
        category,
        label,
        selector,
        selectorType,
        score: Math.round(score),
        matchCount: Math.max(count, 0),
        ...(extra || {})
      });
    }

    // ── 1. ID ───────────────────────────────────────────
    if (id && !looksAutoGenerated(id)) {
      add('id', 'By ID', `#${cssEsc(id)}`, 'css', 95);
      add('id', 'XPath by ID', `//*[@id=${xpEsc(id)}]`, 'xpath', 93);
    }

    // ── 2. Name attribute ───────────────────────────────
    if (name) {
      add('attribute', 'By name', `[name="${name}"]`, 'css', 85);
      add('attribute', 'XPath by name', `//*[@name=${xpEsc(name)}]`, 'xpath', 83);
    }

    // ── 3. Data-testid / data-cy / data-test / data-qa ──
    const testAttrs = ['data-testid', 'data-test-id', 'data-cy', 'data-test', 'data-qa', 'data-automation-id', 'data-e2e'];
    for (const ta of testAttrs) {
      const val = el.getAttribute(ta);
      if (val) {
        add('test-attr', `By ${ta}`, `[${ta}="${val}"]`, 'css', 92);
        add('test-attr', `XPath ${ta}`, `//*[@${ta}=${xpEsc(val)}]`, 'xpath', 90);
      }
    }

    // ── 4. ARIA attributes ──────────────────────────────
    const ariaLabel = el.getAttribute('aria-label');
    const role = el.getAttribute('role');
    const placeholder = el.getAttribute('placeholder');
    const title = el.getAttribute('title');
    const alt = el.getAttribute('alt');
    const href = el.getAttribute('href');
    const src = el.getAttribute('src');
    const action = el.getAttribute('action');
    const value = el.getAttribute('value');
    const forAttr = el.getAttribute('for');

    if (ariaLabel) {
      add('aria', 'By aria-label', `[aria-label="${ariaLabel}"]`, 'css', 88);
      add('aria', 'XPath aria-label', `//*[@aria-label=${xpEsc(ariaLabel)}]`, 'xpath', 86);
    }
    if (role) {
      if (ariaLabel) {
        add('aria', 'Role + aria-label', `[role="${role}"][aria-label="${ariaLabel}"]`, 'css', 87);
      }
      add('aria', 'By role', `[role="${role}"]`, 'css', 60);
    }
    if (placeholder) {
      add('attribute', 'By placeholder', `[placeholder="${placeholder}"]`, 'css', 82);
      add('attribute', 'XPath placeholder', `//*[@placeholder=${xpEsc(placeholder)}]`, 'xpath', 80);
    }
    if (title) {
      add('attribute', 'By title', `[title="${title}"]`, 'css', 75);
      add('attribute', 'XPath title', `//*[@title=${xpEsc(title)}]`, 'xpath', 73);
    }
    if (alt) {
      add('attribute', 'By alt', `${tag}[alt="${alt}"]`, 'css', 78);
    }
    if (forAttr) {
      add('attribute', 'By for', `[for="${forAttr}"]`, 'css', 84);
    }

    // ── 5. Href (for links) ─────────────────────────────
    if (href && tag === 'a') {
      const cleanHref = href.replace(/[?#].*/, '');
      if (cleanHref && cleanHref !== '/' && cleanHref !== '#') {
        if (cleanHref.length < 100) {
          add('attribute', 'By href', `a[href="${cleanHref}"]`, 'css', 80);
        }
        add('attribute', 'XPath href contains', `//a[contains(@href,${xpEsc(cleanHref.split('/').pop() || cleanHref)})]`, 'xpath', 76);
      }
    }

    // ── 6. Text-based locators ──────────────────────────
    // Use own text first (direct text node), then full text
    const textCandidates = [];
    if (ownText && ownText.length > 0) textCandidates.push({ text: ownText, source: 'direct' });
    if (rawText && rawText !== ownText && rawText.length > 0) textCandidates.push({ text: rawText, source: 'full' });

    for (const { text, source } of textCandidates) {
      const phrase = extractPhrase(text, 55);
      const isExact = phrase === text.trim();
      const scoreOffset = source === 'direct' ? 0 : -5;

      if (isExact && phrase.length <= 80) {
        // Exact text match
        add('text', `Text exact (${source})`, `//${tag}[normalize-space()=${xpEsc(phrase)}]`, 'xpath', 78 + scoreOffset);
      }
      if (phrase.length >= 3) {
        // Contains text
        add('text', `Text contains (${source})`, `//${tag}[contains(normalize-space(),${xpEsc(phrase)})]`, 'xpath', 72 + scoreOffset);
      }
    }

    // ── 7. Class-based selectors ────────────────────────
    const staticClasses = classList.filter(c => !isDynamicClass(c));
    const dynamicClasses = classList.filter(c => isDynamicClass(c));

    if (staticClasses.length > 0) {
      // Single most specific static class
      for (const cls of staticClasses.slice(0, 3)) {
        add('class', `By class .${cls}`, `${tag}.${cssEsc(cls)}`, 'css', 55);
      }
      // Combined static classes
      if (staticClasses.length >= 2) {
        const combo = staticClasses.slice(0, 3).map(c => `.${cssEsc(c)}`).join('');
        add('class', 'Combined classes', `${tag}${combo}`, 'css', 62);
      }
    }

    // Dynamic classes — still useful but flagged
    for (const cls of dynamicClasses.slice(0, 2)) {
      add('class', `Dynamic class .${cls}`, `//${tag}[contains(@class,${xpEsc(cls)})]`, 'xpath', 35, { warning: 'Class may be dynamic — verify stability across builds' });
    }

    // ── 8. Type attribute for inputs ────────────────────
    if (type && (tag === 'input' || tag === 'button')) {
      add('attribute', `By type`, `${tag}[type="${type}"]`, 'css', 50);
      if (name) {
        add('attribute', 'Type + name', `${tag}[type="${type}"][name="${name}"]`, 'css', 86);
      }
    }

    // ── 9. Value attribute (buttons / inputs) ───────────
    if (value && (tag === 'input' || tag === 'button')) {
      add('attribute', 'By value', `${tag}[value="${value}"]`, 'css', 70);
    }

    // ── 10. Source / action attributes ──────────────────
    if (src && (tag === 'img' || tag === 'script' || tag === 'iframe' || tag === 'video' || tag === 'source')) {
      const srcTail = src.split('/').pop().split('?')[0];
      if (srcTail && srcTail.length > 3) {
        add('attribute', 'By src (tail)', `${tag}[src*="${srcTail}"]`, 'css', 68);
      }
    }
    if (action && tag === 'form') {
      add('attribute', 'By action', `form[action*="${action.split('/').pop()}"]`, 'css', 72);
    }

    // ── 11. Child-anchor strategy ───────────────────────
    // For containers: look at child <a>, <b>, <strong>, <img> for resilient locators
    const childAnchors = el.querySelectorAll(':scope > a, :scope > b, :scope > strong, :scope a, :scope img[alt]');
    const seenChildSels = new Set();
    for (const child of Array.from(childAnchors).slice(0, 4)) {
      const ctag = child.tagName.toLowerCase();
      if (ctag === 'a') {
        const ch = child.getAttribute('href');
        if (ch && ch.length > 1 && ch.length < 150) {
          const key = `a-href-${ch}`;
          if (!seenChildSels.has(key)) {
            seenChildSels.add(key);
            const hrefPart = ch.split('/').filter(Boolean).pop() || ch;
            add('hierarchy', 'Via child link href', `//${tag}[.//a[contains(@href,${xpEsc(hrefPart)})]]`, 'xpath', 74);
          }
        }
        const linkText = child.textContent.trim();
        if (linkText && linkText.length > 1 && linkText.length < 80) {
          const key = `a-text-${linkText}`;
          if (!seenChildSels.has(key)) {
            seenChildSels.add(key);
            add('hierarchy', 'Via child link text', `//${tag}[.//a[contains(text(),${xpEsc(extractPhrase(linkText, 40))})]]`, 'xpath', 72);
          }
        }
      }
      if (ctag === 'b' || ctag === 'strong') {
        const bText = child.textContent.trim();
        if (bText && bText.length > 1 && bText.length < 80) {
          const key = `b-${bText}`;
          if (!seenChildSels.has(key)) {
            seenChildSels.add(key);
            add('hierarchy', `Via child <${ctag}> text`, `//${tag}[.//${ctag}[contains(text(),${xpEsc(extractPhrase(bText, 40))})]]`, 'xpath', 70);
          }
        }
      }
      if (ctag === 'img') {
        const imgAlt = child.getAttribute('alt');
        if (imgAlt) {
          const key = `img-alt-${imgAlt}`;
          if (!seenChildSels.has(key)) {
            seenChildSels.add(key);
            add('hierarchy', 'Via child img alt', `//${tag}[.//img[@alt=${xpEsc(imgAlt)}]]`, 'xpath', 69);
          }
        }
      }
    }

    // ── 12. Parent-child hierarchy ──────────────────────
    const parent = el.parentElement;
    if (parent) {
      const pTag = parent.tagName.toLowerCase();
      const pId  = parent.id;
      const nth  = nthIndex(el);

      if (pId && !looksAutoGenerated(pId)) {
        add('hierarchy', 'Parent ID > tag', `#${cssEsc(pId)} > ${tag}:nth-child(${nth})`, 'css', 82);
        add('hierarchy', 'XPath parent ID', `//*[@id=${xpEsc(pId)}]/${tag}[${nth}]`, 'xpath', 80);
      }

      // Grandparent with ID
      const gp = parent.parentElement;
      if (gp && gp.id && !looksAutoGenerated(gp.id)) {
        add('hierarchy', 'Grandparent ID path', `#${cssEsc(gp.id)} > ${pTag}:nth-child(${nthIndex(parent)}) > ${tag}:nth-child(${nth})`, 'css', 72);
      }

      // Parent with unique class
      const pStaticClasses = Array.from(parent.classList || []).filter(c => !isDynamicClass(c));
      if (pStaticClasses.length > 0) {
        const pCls = pStaticClasses[0];
        if (cssCount(`${pTag}.${cssEsc(pCls)}`) <= 3) {
          add('hierarchy', 'Parent class > child', `${pTag}.${cssEsc(pCls)} > ${tag}:nth-child(${nth})`, 'css', 65);
        }
      }
    }

    // ── 13. nth-child / nth-of-type ─────────────────────
    {
      const nth = nthIndex(el);
      let typeIdx = 1;
      let sib = el.previousElementSibling;
      while (sib) { if (sib.tagName === el.tagName) typeIdx++; sib = sib.previousElementSibling; }

      if (parent) {
        const pTag = parent.tagName.toLowerCase();
        add('positional', 'nth-child', `${pTag} > ${tag}:nth-child(${nth})`, 'css', 35);
        add('positional', 'nth-of-type', `${pTag} > ${tag}:nth-of-type(${typeIdx})`, 'css', 34);
        add('positional', 'XPath position', `//${pTag}/${tag}[${typeIdx}]`, 'xpath', 32);
      }
    }

    // ── 14. Absolute XPath (always fragile) ─────────────
    add('absolute', 'Absolute XPath', absoluteXpath(el), 'xpath', 10);

    // ── 15. Full CSS path via nth-child ─────────────────
    {
      const chain = [];
      let cur = el;
      let depth = 0;
      while (cur && cur.nodeType === 1 && cur !== document.documentElement && depth < 6) {
        const t = cur.tagName.toLowerCase();
        chain.unshift(`${t}:nth-child(${nthIndex(cur)})`);
        cur = cur.parentElement;
        depth++;
      }
      if (chain.length > 1) {
        add('absolute', 'CSS full path', chain.join(' > '), 'css', 12);
      }
    }

    // ── Sort by score descending ────────────────────────
    locators.sort((a, b) => b.score - a.score);

    // ── Tier assignment ─────────────────────────────────
    for (const loc of locators) {
      if (loc.score >= 75) loc.tier = 'stable';
      else if (loc.score >= 45) loc.tier = 'moderate';
      else loc.tier = 'fragile';
    }

    // ── Element metadata ────────────────────────────────
    return {
      tag,
      id: id || null,
      classes: classList,
      attributes: attrs,
      textPreview: extractPhrase(rawText, 120),
      rect: { x: Math.round(rect.x), y: Math.round(rect.y), w: Math.round(rect.width), h: Math.round(rect.height) },
      locators
    };
  }

  /* Get direct (own) text nodes only */
  function getDirectText(el) {
    let t = '';
    for (const node of el.childNodes) {
      if (node.nodeType === Node.TEXT_NODE) t += node.textContent;
    }
    return t.replace(/\s+/g, ' ').trim();
  }

  // ═══════════════════════════════════════════════════════════════
  //  OVERLAY
  // ═══════════════════════════════════════════════════════════════

  function ensureOverlay() {
    if (overlayEl) return;
    overlayEl = document.createElement('div');
    overlayEl.id = OVR_ID;
    tagEl = document.createElement('div');
    tagEl.id = TAG_ID;
    overlayEl.appendChild(tagEl);
    document.documentElement.appendChild(overlayEl);
  }

  function showOverlay(el) {
    ensureOverlay();
    const r = el.getBoundingClientRect();
    Object.assign(overlayEl.style, {
      position: 'fixed',
      top: r.top + 'px',
      left: r.left + 'px',
      width: r.width + 'px',
      height: r.height + 'px',
      display: 'block',
      pointerEvents: 'none',
      zIndex: '2147483646',
      outline: '2px solid #6366f1',
      background: 'rgba(99,102,241,0.07)',
      boxSizing: 'border-box',
      transition: 'top .08s, left .08s, width .08s, height .08s'
    });
    const classes = Array.from(el.classList || []).slice(0, 2).join('.');
    tagEl.textContent = el.tagName.toLowerCase() + (el.id ? `#${el.id.slice(0, 20)}` : '') + (classes ? `.${classes.slice(0, 30)}` : '');
    Object.assign(tagEl.style, {
      position: 'absolute',
      bottom: '100%',
      left: '0',
      background: '#6366f1',
      color: '#fff',
      fontSize: '10px',
      fontFamily: 'monospace',
      padding: '2px 6px',
      borderRadius: '3px 3px 0 0',
      whiteSpace: 'nowrap',
      maxWidth: '300px',
      overflow: 'hidden',
      textOverflow: 'ellipsis'
    });
  }

  function flashGreen() {
    if (!overlayEl) return;
    overlayEl.style.outline = '2px solid #10b981';
    overlayEl.style.background = 'rgba(16,185,129,0.12)';
    setTimeout(() => {
      if (overlayEl) {
        overlayEl.style.outline = '2px solid #6366f1';
        overlayEl.style.background = 'rgba(99,102,241,0.07)';
      }
    }, 400);
  }

  function hideOverlay() {
    if (overlayEl) overlayEl.style.display = 'none';
  }

  // ═══════════════════════════════════════════════════════════════
  //  FLASH LOCATORS (highlight from panel)
  // ═══════════════════════════════════════════════════════════════

  let flashedEls = [];

  function clearFlashed() {
    flashedEls.forEach(el => {
      if (el && el._llPrevOutline !== undefined) {
        el.style.outline = el._llPrevOutline;
        delete el._llPrevOutline;
      }
    });
    flashedEls = [];
  }

  function flashSelector(selector, selectorType) {
    clearFlashed();
    let els = [];
    try {
      if (selectorType === 'xpath') {
        const r = document.evaluate(selector, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
        for (let i = 0; i < r.snapshotLength && i < 50; i++) {
          const n = r.snapshotItem(i);
          if (n && n.nodeType === 1) els.push(n);
        }
      } else {
        els = Array.from(document.querySelectorAll(selector)).slice(0, 50);
      }
    } catch { return; }

    for (const el of els) {
      el._llPrevOutline = el.style.outline || '';
      el.style.outline = '2px solid #f59e0b';
      flashedEls.push(el);
    }

    if (els[0]) els[0].scrollIntoView({ behavior: 'smooth', block: 'center' });
  }

  // ═══════════════════════════════════════════════════════════════
  //  PICKER + PASSIVE MODE
  // ═══════════════════════════════════════════════════════════════

  const state = { picking: false, passive: false, lastTarget: null };

  /* ── PICK MODE: hover highlights, click captures ──── */
  function onPickMove(e) {
    const target = e.target;
    if (!target || target === overlayEl || target === tagEl) return;
    state.lastTarget = target;
    showOverlay(target);
  }

  function onPickClick(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    e.stopPropagation();

    // FIX #1: Use e.target directly, NOT the hovered state.
    // On fast clicks, mousemove may not have fired yet.
    let target = e.target;
    if (target === overlayEl || target === tagEl) {
      target = state.lastTarget || document.elementFromPoint(e.clientX, e.clientY);
    }
    if (!target || target === overlayEl || target === tagEl) return;

    flashGreen();
    stopPick();

    const payload = generateLocators(target);
    chrome.runtime.sendMessage({ type: 'locatorsGenerated', payload });
  }

  function onPickKey(e) {
    if (e.key === 'Escape') {
      stopPick();
      chrome.runtime.sendMessage({ type: 'pickingCancelled' });
    }
  }

  function startPick() {
    state.picking = true;
    ensureOverlay();
    overlayEl.style.display = '';
    document.addEventListener('mousemove', onPickMove, true);
    document.addEventListener('click', onPickClick, true);
    document.addEventListener('keydown', onPickKey, true);
    document.documentElement.style.cursor = 'crosshair';
  }

  function stopPick() {
    state.picking = false;
    hideOverlay();
    document.removeEventListener('mousemove', onPickMove, true);
    document.removeEventListener('click', onPickClick, true);
    document.removeEventListener('keydown', onPickKey, true);
    document.documentElement.style.cursor = '';
  }

  /* ── PASSIVE MODE: captures every page click silently ──── */
  function onPassiveClick(e) {
    if (!state.passive) return;
    if (state.picking) return; // Pick mode takes priority

    let target = e.target;
    if (target === overlayEl || target === tagEl) return;
    if (!target) return;

    // Brief green flash on the clicked element
    ensureOverlay();
    const r = target.getBoundingClientRect();
    Object.assign(overlayEl.style, {
      position: 'fixed',
      top: r.top + 'px', left: r.left + 'px',
      width: r.width + 'px', height: r.height + 'px',
      display: 'block', pointerEvents: 'none',
      zIndex: '2147483646',
      outline: '2px solid #10b981',
      background: 'rgba(16,185,129,0.08)',
      boxSizing: 'border-box'
    });
    tagEl.textContent = target.tagName.toLowerCase();
    Object.assign(tagEl.style, {
      position: 'absolute', bottom: '100%', left: '0',
      background: '#10b981', color: '#fff',
      fontSize: '10px', fontFamily: 'monospace',
      padding: '2px 6px', borderRadius: '3px 3px 0 0',
      whiteSpace: 'nowrap'
    });
    setTimeout(() => hideOverlay(), 600);

    // Generate for ALL element types — no filtering
    const payload = generateLocators(target);
    chrome.runtime.sendMessage({ type: 'locatorsGenerated', payload });
  }

  // Passive listener is always active but gated by state.passive flag
  document.addEventListener('click', onPassiveClick, true);

  // ═══════════════════════════════════════════════════════════════
  //  VALIDATE SELECTOR
  // ═══════════════════════════════════════════════════════════════

  function validateSelector(selector, selectorType) {
    let count = -1;
    let error = null;
    try {
      count = selectorType === 'xpath' ? xpCount(selector) : cssCount(selector);
    } catch (err) {
      error = err.message;
    }
    return { selector, selectorType, count, error };
  }

  // ═══════════════════════════════════════════════════════════════
  //  MESSAGE HANDLER
  // ═══════════════════════════════════════════════════════════════

  chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
    switch (msg.type) {
      case 'ping':
        sendResponse({ pong: true });
        break;
      case 'startPicking':
        startPick();
        sendResponse({ ok: true });
        break;
      case 'stopPicking':
        stopPick();
        sendResponse({ ok: true });
        break;
      case 'setPassive':
        state.passive = !!msg.enabled;
        sendResponse({ ok: true });
        break;
      case 'flashLocator':
        flashSelector(msg.selector, msg.selectorType);
        sendResponse({ ok: true });
        break;
      case 'clearFlash':
        clearFlashed();
        sendResponse({ ok: true });
        break;
      case 'validateSelector':
        sendResponse(validateSelector(msg.selector, msg.selectorType));
        break;
      default:
        sendResponse({ ok: false });
    }
    return true; // Keep channel open for async
  });

})();
